### PR TITLE
Barreleye XML updates

### PR DESCRIPTION
**Pull request by johnhihi**

### CODE REVIEW

**Comment by williamspatrick** [comment]
@nkskjames - Anything you want to look over here?

**Comment by williamspatrick** [comment]
@johnhihi - Will you also be contributing Barreleye support in the op-build repository after this gets merged?

**Comment by johnhihi** [comment]
@williamspatrick 
We will keep contributing Barreleye support in the op-build in the future, but now we have some issues and feature not complete. Please see following description:

Issue 1: VPD Caching broken on multiple socket, single CVPD systems (Barreleye) [1]
For issue 1, now we use a workaround patch in "openpower/custom/patches/hostboot/hostboot-0099-fix-vpd-issue.patch" [2]. If we merge this to op-build, all the power 8 platform may build this patch into pnor, maybe there are some side effects. For this one, we can remove this patch after issue fixed.

Issue 2: PXA95X command difference between Barreleye and other platforms.
For issue 2, Barreleye system use PXA9536 instead PXA9535 for gpio_exp, there are different command code for these two PXA95X chips. Currently we make a patch in "openpower/package/hostboot/hostboot-0011-foxconn-pxa95x-command.patch" [3]. If we merge this into op-build, all other platform suffers.

Issue 3: Barreleye platform has add to Skiboot.
For issue 3, currently we make a patch in "openpower/package/skiboot/skiboot-0001-add-barreleye-platform.patch" [4]. This patch will remove once skiboot add barreleye platform. @jk-ozlabs makes this patch first, and we done some modify to fit op-build v1.6.

Un-complete feature 1: BT interface not work yet.
Due to BT interface not work yet, Barreleye will hang at skiboot. Currently we comment out "CONFIG_IPMI_HANDLER", "CONFIG_IPMI_DEVICE_INTERFACE" and "CONFIG_IPMI_POWERNV" in "openpower/configs/linux/skiroot_defconfig". We will remove this change until BT feature complete.

[1] https://github.com/open-power/hostboot/issues/29
[2] https://github.com/bogatseng/op-build/blob/master/openpower/custom/patches/hostboot/hostboot-0099-fix-vpd-issue.patch
[3] https://github.com/bogatseng/op-build/blob/master/openpower/package/hostboot/hostboot-0011-foxconn-pxa95x-command.patch
[4] https://github.com/bogatseng/op-build/blob/master/openpower/package/skiboot/skiboot-0001-add-barreleye-platform.patch

**Comment by williamspatrick** [comment]
@johnhihi - Understand.  I would like to see patch 3 you mention above.  We might be able to do something in Hostboot (or the MRW) to identify the difference between the 9535 and 9536 chip and support both.

I am going to create a 'team' on this github project and give you control to add and remove people to it.  That 'team' will have direct authority over this barreleye-xml repository.

**Comment by johnhihi** [comment]
@williamspatrick - Thank you for your feedback. Patch 3 is here.
https://github.com/bogatseng/op-build/blob/master/openpower/package/hostboot/hostboot-0011-foxconn-pxa95x-command.patch

**Comment by williamspatrick** [comment]
@johnhihi - Thank you too.  I opened open-power/hostboot#35 to try to
get this support natively.

On Mon, Sep 14, 2015 at 06:12:25PM -0700, johnhihi wrote:

> @williamspatrick - Thank you for your feedback. Patch 3 is here.
> https://github.com/bogatseng/op-build/blob/master/openpower/package/hostboot/hostboot-0011-foxconn-pxa95x-command.patch
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/open-power/barreleye-xml/pull/1#issuecomment-140245405

## 

Patrick Williams

**Pull request merged**
